name: Smart Energy Monitoring CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on pushes to 'main' branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Ensure Python 3.9 is installed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        echo "Running tests..."
        pytest tests/

    - name: Build Docker Image
      run: |
        echo "Building Docker image..."
        docker build -t smart-energy-app .

    - name: Run Docker Container Test
      run: |
        echo "Running Docker container for testing..."
        docker run -d --name smart-energy-container -p 5000:5000 smart-energy-app
        echo "Testing application availability..."
        curl --fail http://localhost:5000 || exit 1

    - name: Clean Up Docker Container
      if: always()  # Ensure cleanup happens regardless of success or failure
      run: |
        echo "Stopping and removing Docker container..."
        docker stop smart-energy-container || echo "Container already stopped."
        docker rm smart-energy-container || echo "Container already removed."
        docker rmi smart-energy-app || echo "Image already removed."