name: Smart Energy Monitoring CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on pushes to 'main' branch
  pull_request:
    branches:
      - main  # Optional: Trigger pipeline on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        # Add specific test commands for your project
        pytest tests/

    - name: Build Docker Image
      run: |
        docker build -t smart-energy-app .

    - name: Run Docker Container Test
      run: |
        docker run -d -p 5000:5000 smart-energy-app
        curl --fail http://localhost:5000 || exit 1

    - name: Clean Up Docker Container
      run: |
        docker stop $(docker ps -q)
        docker rm $(docker ps -aq)